### PR TITLE
DPDK Backend: Add target_name to specify table name as in spec file

### PR DESCRIPTION
**Pull request by usha1830**
Changes for 
https://wiki.ith.intel.com/pages/viewpage.action?pageId=2253848776#ChangeRequests-Change_Request_CR00010

A new field target_name is added to specify the table name as it is present in the spec file (this is the originalName). Existing field "name" specifies the control plane name of the table, this is same as the name in bfrt json file.

 "tables" : [
    {
      "name" : "ingress.ipv4_host",
       **"target_name" : "ingress.ipv4_host_1",**
       "direction" : "ingress",

        ....

        }
...
]

### CODE REVIEW

**Review by github-sajan — COMMENTED** [review]
Please add one  testcase to see the changes

**Review by syogender — APPROVED** [review]
Looks good

**Comment by usha1830** [comment]
> Please add one testcase to see the changes

All existing tests will be affected. Attached diff report for output from latest linux networking program. Please remove the .txt extension and view html.
[Report.html.txt](https://github.com/usha1830/p4c/files/8820482/Report.html.txt)

**Review by github-sajan — APPROVED** [review]
Looks fine

**Review by psivanup — APPROVED** [review]
Looks good to me.

**Comment by usha1830** [comment]
Reopening this as SDE team has found some issue w.r.t table names for compiler generated/modified tables (for example tables for action selector and action profile).

**Comment by usha1830** [comment]
Fix confirmed by SDE team and changes merged to upstream main.

**Pull request closed without merging**
