### PR TITLE
DPDK Backend : Minor fixes

### PR DESCRIPTION
**Pull request by usha1830**
1) Error if learner table exists with non-exact match keys 
2) Removed explicit from constructor with more than one parameters 
3) Typo in condition check in context json generation
`4) Added new test

### CODE REVIEW

**Review by github-sajan — COMMENTED** [review]
stderr file is empty. The testcase added is an error-case ?

**Comment by usha1830** [comment]
> stderr file is empty. The testcase added is an error-case ?

Yes . Working on fixing the test infra as well. Currently, the stderr is empty for all error cases as well.  stderr file is actually for errors/warnings from p4test backend. For dpdk, we use a file called -error which is also empty in most cases. 
Current way of adding negative tests is to add them in the Xfail list with expected regex in the error output

**Review by github-sajan — APPROVED** [review]
Looks fine

**Review by maheswari-s — APPROVED** [review]
Looks fine

**Comment by usha1830** [comment]
Closing as upstreamed

**Pull request closed without merging**
