### PR TITLE
Update pna.p4 to include packet length as optional parameter

### PR DESCRIPTION
**Pull request by usha1830**
Packet length parameter is required by dpdk for Indirect counters and Meters.

### CODE REVIEW

**Review by syogender — APPROVED** [review]
Looks good

**Review by maheswari-s — APPROVED** [review]
Looks fine

**Comment by kamleshbhalui** [comment]
I think we should create separate , like we did for psa.p4?

**Comment by usha1830** [comment]
> I think we should create separate , like we did for psa.p4?

Right now, dpdk is the only target using PNA. For PNA, we can try to have this added to the specification. If not,  we can take a call in future and update similar to PSA.

**Review by psivanup — APPROVED** [review]
The changes look fine to me.

**Comment by usha1830** [comment]
Closing as upstreamed

**Pull request closed without merging**
